spring.application.name=userservice Demo User service for understand the git 
#server.port= 8082

spring.profiles.active=local

<<<<<<< HEAD
#new feature 
=======
# testing 
>>>>>>> 21d89dd26e93014c682561851f32c3e8c6579dc8

